### ISSUE TITLE
Create CI/CD pipeline via GitHub-actions to update old Subreddit stylesheet

### ISSUE THREAD

**Issue by Bhupesh-V** [developersIndia/stylesheet#4]
### Feature details?

At the moment.
- An admin has to manually update the CSS whenever changes are made to the CSS.
- Since our Subreddit stylesheet is open-source, it's possible more folks may want to contribute, this raises the need to continuously deploy the updated CSS without admin intervention.

Good to have (but not necessary):
- Check if it's possible to upload images to reddit via praw as well.

Starting point PRAW Docs: https://praw.readthedocs.io/en/stable/code_overview/models/subreddit.html#praw.models.Subreddit.stylesheet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LinearArray** [comment]
/r/Anime uses something like this https://github.com/r-anime/stylesheet/blob/main/.github/workflows/build-and-deploy.yml
